"""PDF / 文本报告生成（与 src/CMR/calculate.py 对齐）"""

import os
from datetime import datetime
from typing import Dict

from app.config import LV_WALL_SEGMENTS, RV_WALL_SEGMENTS


def _fmt(val, precision=2):
    if val is None:
        return "-"
    if isinstance(val, float):
        return f"{val:.{precision}f}"
    return str(val)


def _generate_text_report(metrics: Dict, output_path: str) -> str:
    """当 reportlab 不可用时，生成纯文本格式的完整报告"""
    txt_path = output_path.replace('.pdf', '.txt')
    os.makedirs(os.path.dirname(txt_path), exist_ok=True)

    L = []
    L.append("=" * 70)
    L.append("  CARDIAC MAGNETIC RESONANCE IMAGING REPORT")
    L.append("=" * 70)
    L.append(f"  Generated By : Cardiac Agent")
    L.append(f"  Date         : {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    L.append(f"  Method       : AI-Powered Segmentation + Metrics")
    L.append("")

    # 1. Chamber Dimensions
    L.append("-" * 70)
    L.append("  1. CHAMBER DIMENSIONS")
    L.append("-" * 70)
    L.append(f"  {'Chamber':<30} {'Long(mm)':>10}  {'Source':>8}")
    for chamber, ld_key, src in [
        ("Left Atrium (LA)", "LA_LD", "4CH"),
        ("Right Atrium (RA)", "RA_LD", "4CH"),
        ("Left Ventricle (LV)", "LV_LD", "SA"),
        ("Right Ventricle (RV)", "RV_LD", "SA"),
    ]:
        ld = metrics.get(ld_key)
        if ld is not None:
            L.append(f"  {chamber:<30} {_fmt(ld):>10}  {src:>8}")
    L.append("")

    # 2. LV Wall Thickness
    has_lv_wall = any(metrics.get(f"{p}_{n:02d}_mean") is not None for p, n, _, _ in LV_WALL_SEGMENTS)
    has_apex = metrics.get("LV_TP_17_mean") is not None
    if has_lv_wall or has_apex:
        L.append("-" * 70)
        L.append("  2. LV MYOCARDIAL WALL THICKNESS (17-Segment Model, from Cine SA)")
        L.append("-" * 70)
        L.append(f"  {'Segment':<30} {'Mean(mm)':>10} {'Max(mm)':>10} {'Min(mm)':>10}")

        for label, segments in [("Basal Segments (1-6)", LV_WALL_SEGMENTS[:6]),
                                ("Mid Segments (7-12)", LV_WALL_SEGMENTS[6:12]),
                                ("Apical Segments (13-16)", LV_WALL_SEGMENTS[12:])]:
            L.append(f"  --- {label} ---")
            for prefix, num, en_name, _ in segments:
                mean_v = metrics.get(f"{prefix}_{num:02d}_mean")
                max_v = metrics.get(f"{prefix}_{num:02d}_max")
                min_v = metrics.get(f"{prefix}_{num:02d}_min")
                if mean_v is not None or max_v is not None:
                    L.append(f"  {en_name:<30} {_fmt(mean_v):>10} {_fmt(max_v):>10} {_fmt(min_v):>10}")

        if has_apex:
            L.append("  --- Apex (Segment 17, from Cine 4CH) ---")
            L.append(f"  {'Apex':<30} {_fmt(metrics.get('LV_TP_17_mean')):>10} "
                     f"{_fmt(metrics.get('LV_TP_17_max')):>10} {_fmt(metrics.get('LV_TP_17_min')):>10}")
        L.append("")

    # 3. RV Wall Thickness
    has_rv_wall = any(metrics.get(k) is not None for k, _ in RV_WALL_SEGMENTS)
    if has_rv_wall:
        L.append("-" * 70)
        L.append("  3. RV WALL THICKNESS (from Cine 4CH)")
        L.append("-" * 70)
        L.append(f"  {'Segment':<30} {'Thickness(mm)':>14}")
        for key, name in RV_WALL_SEGMENTS:
            val = metrics.get(key)
            if val is not None:
                L.append(f"  {name:<30} {_fmt(val):>14}")
        L.append("")

    # 4. LV Function
    L.append("-" * 70)
    L.append("  4. LEFT VENTRICLE (LV) FUNCTION (from Cine SA)")
    L.append("-" * 70)
    L.append(f"  {'Parameter':<30} {'Value':>10} {'Unit':>8} {'Normal':>12}")
    for key, name, unit, normal in [
        ('LV_EF', 'Ejection Fraction', '%', '55-70'),
        ('LV_EDV', 'End-Diastolic Volume', 'mL', '56-155'),
        ('LV_ESV', 'End-Systolic Volume', 'mL', '19-58'),
        ('LV_SV', 'Stroke Volume', 'mL', '55-100'),
        ('LV_CO', 'Cardiac Output', 'L/min', '4.0-8.0'),
        ('LV_Mass', 'Myocardial Mass', 'g', '85-190'),
    ]:
        val = metrics.get(key)
        if val is not None:
            L.append(f"  {name:<30} {_fmt(val):>10} {unit:>8} {normal:>12}")
    L.append("")

    # 5. RV Function
    L.append("-" * 70)
    L.append("  5. RIGHT VENTRICLE (RV) FUNCTION (from Cine SA)")
    L.append("-" * 70)
    L.append(f"  {'Parameter':<30} {'Value':>10} {'Unit':>8} {'Normal':>12}")
    for key, name, unit, normal in [
        ('RV_EF', 'Ejection Fraction', '%', '40-65'),
        ('RV_EDV', 'End-Diastolic Volume', 'mL', '88-227'),
        ('RV_ESV', 'End-Systolic Volume', 'mL', '35-100'),
        ('RV_SV', 'Stroke Volume', 'mL', '55-100'),
        ('RV_CO', 'Cardiac Output', 'L/min', '4.0-8.0'),
    ]:
        val = metrics.get(key)
        if val is not None:
            L.append(f"  {name:<30} {_fmt(val):>10} {unit:>8} {normal:>12}")
    L.append("")

    # 6. Conclusions
    L.append("-" * 70)
    L.append("  6. AUTOMATED ASSESSMENT")
    L.append("-" * 70)
    lv_ef = metrics.get('LV_EF')
    if lv_ef is not None:
        if lv_ef >= 50:
            L.append(f"  * Normal LV systolic function (LVEF: {lv_ef:.1f}%)")
        elif lv_ef >= 40:
            L.append(f"  * Mild LV systolic dysfunction (LVEF: {lv_ef:.1f}%)")
        elif lv_ef >= 30:
            L.append(f"  * Moderate LV systolic dysfunction (LVEF: {lv_ef:.1f}%)")
        else:
            L.append(f"  * Severe LV systolic dysfunction (LVEF: {lv_ef:.1f}%)")
    rv_ef = metrics.get('RV_EF')
    if rv_ef is not None:
        if rv_ef >= 45:
            L.append(f"  * Normal RV systolic function (RVEF: {rv_ef:.1f}%)")
        elif rv_ef >= 35:
            L.append(f"  * Mild RV systolic dysfunction (RVEF: {rv_ef:.1f}%)")
        else:
            L.append(f"  * Moderate-severe RV systolic dysfunction (RVEF: {rv_ef:.1f}%)")
    basal_vals = [metrics.get(f"LV_BS_{i:02d}_mean") for i in range(1, 7)]
    basal_vals = [v for v in basal_vals if v is not None]
    if basal_vals:
        avg_t = sum(basal_vals) / len(basal_vals)
        if avg_t > 12:
            L.append(f"  * LV wall thickening (avg basal: {avg_t:.1f}mm)")
        elif avg_t < 6:
            L.append(f"  * LV wall thinning (avg basal: {avg_t:.1f}mm)")
        else:
            L.append(f"  * Normal LV wall thickness (avg basal: {avg_t:.1f}mm)")
    L.append("")
    L.append("  Note: AI-assisted analysis. Clinical correlation recommended.")
    L.append("=" * 70)

    with open(txt_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(L))

    print(f"文本报告已生成(reportlab不可用回退): {txt_path}")
    return txt_path


def generate_cardiac_report_pdf(
    metrics: Dict,
    report_data: Dict = None,
    output_path: str = "cardiac_report.pdf",
    seg_info: Dict = None,
) -> str:
    """生成完整心脏功能评估报告（PDF 优先，自动回退到文本报告）"""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib import colors as rl_colors
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont
        HAS_REPORTLAB = True
    except ImportError:
        HAS_REPORTLAB = False
        print("reportlab未安装，将回退到文本报告格式")

    if not HAS_REPORTLAB:
        return _generate_text_report(metrics, output_path)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    for fp in ['/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
               '/System/Library/Fonts/Helvetica.ttc', 'C:/Windows/Fonts/arial.ttf']:
        if os.path.exists(fp):
            try:
                pdfmetrics.registerFont(TTFont('ReportFont', fp))
                break
            except:
                continue

    doc = SimpleDocTemplate(output_path, pagesize=A4)
    story = []
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('RT', parent=styles['Heading1'],
        fontName='Helvetica-Bold', fontSize=18, spaceAfter=30, alignment=1)
    h1 = ParagraphStyle('RH1', parent=styles['Heading1'],
        fontName='Helvetica-Bold', fontSize=14, spaceAfter=12, spaceBefore=20)
    h2 = ParagraphStyle('RH2', parent=styles['Heading2'],
        fontName='Helvetica-Bold', fontSize=11, spaceAfter=8, spaceBefore=12)
    ns = ParagraphStyle('RN', parent=styles['Normal'],
        fontName='Helvetica', fontSize=9, spaceAfter=4)

    HEADER_BG = rl_colors.HexColor('#4472C4')
    ROW_ALT = rl_colors.HexColor('#D6E4F0')

    def _make_table(data, col_widths, header_bg=HEADER_BG):
        t = Table(data, colWidths=col_widths)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), header_bg),
            ('TEXTCOLOR', (0, 0), (-1, 0), rl_colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, rl_colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [rl_colors.white, ROW_ALT]),
        ]))
        return t

    # Title
    story.append(Paragraph("Cardiac Magnetic Resonance Imaging Report", title_style))
    story.append(Spacer(1, 10))

    # 1. Exam Info
    story.append(Paragraph("1. Examination Information", h1))
    exam_data = [
        ['Generated By', 'Cardiac Agent', 'Date', datetime.now().strftime('%Y-%m-%d %H:%M')],
        ['Analysis Type', 'Automated CMR Analysis', 'Method', 'AI Segmentation + Metrics'],
    ]
    et = Table(exam_data, colWidths=[1.2*inch, 1.5*inch, 1.0*inch, 1.8*inch])
    et.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), rl_colors.lightgrey),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'), ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 8), ('GRID', (0, 0), (-1, -1), 0.5, rl_colors.grey),
    ]))
    story.append(et)
    story.append(Spacer(1, 15))

    # 2. Chamber Dimensions
    dim_data = [['Chamber', 'Long Diameter (mm)', 'Source']]
    for chamber, ld_key, src in [
        ("Left Atrium (LA)", "LA_LD", "4CH"),
        ("Right Atrium (RA)", "RA_LD", "4CH"),
        ("Left Ventricle (LV)", "LV_LD", "SA"),
        ("Right Ventricle (RV)", "RV_LD", "SA"),
    ]:
        ld = metrics.get(ld_key)
        if ld is not None:
            dim_data.append([chamber, _fmt(ld), src])

    if len(dim_data) > 1:
        story.append(Paragraph("2. Chamber Dimensions", h1))
        story.append(_make_table(dim_data, [2.0*inch, 1.5*inch, 0.8*inch]))
        story.append(Spacer(1, 10))

    # 3. Myocardial Wall Thickness
    story.append(Paragraph("3. Myocardial Wall Thickness", h1))

    for sub_title, segments in [
        ("3.1 LV Basal Segments (from Cine SA)", LV_WALL_SEGMENTS[:6]),
        ("3.2 LV Mid Segments (from Cine SA)", LV_WALL_SEGMENTS[6:12]),
        ("3.3 LV Apical Segments (from Cine SA)", LV_WALL_SEGMENTS[12:]),
    ]:
        header_label = sub_title.split(" ", 1)[1].split("(")[0].strip()
        rows = [[header_label, 'Mean (mm)', 'Max (mm)', 'Min (mm)']]
        for prefix, num, en_name, _ in segments:
            mean_v = metrics.get(f"{prefix}_{num:02d}_mean")
            max_v = metrics.get(f"{prefix}_{num:02d}_max")
            min_v = metrics.get(f"{prefix}_{num:02d}_min")
            if mean_v is not None or max_v is not None:
                rows.append([en_name, _fmt(mean_v), _fmt(max_v), _fmt(min_v)])
        if len(rows) > 1:
            story.append(Paragraph(sub_title, h2))
            story.append(_make_table(rows, [1.8*inch, 1.0*inch, 1.0*inch, 1.0*inch]))
            story.append(Spacer(1, 8))

    apex_mean = metrics.get("LV_TP_17_mean")
    apex_max = metrics.get("LV_TP_17_max")
    apex_min = metrics.get("LV_TP_17_min")
    if apex_mean is not None or apex_max is not None:
        lv_apex = [['LV Apex (Seg 17)', 'Mean (mm)', 'Max (mm)', 'Min (mm)'],
                    ['Apex', _fmt(apex_mean), _fmt(apex_max), _fmt(apex_min)]]
        story.append(Paragraph("3.4 LV Apex - Segment 17 (from Cine 4CH)", h2))
        story.append(_make_table(lv_apex, [1.8*inch, 1.0*inch, 1.0*inch, 1.0*inch]))
        story.append(Spacer(1, 8))

    rv_wall = [['RV Wall Segment', 'Thickness (mm)']]
    for key, name in RV_WALL_SEGMENTS:
        val = metrics.get(key)
        if val is not None:
            rv_wall.append([name, _fmt(val)])
    if len(rv_wall) > 1:
        story.append(Paragraph("3.5 RV Wall Thickness (from Cine 4CH)", h2))
        story.append(_make_table(rv_wall, [2.5*inch, 1.2*inch]))
        story.append(Spacer(1, 10))

    # 4. Ventricular Function
    story.append(Paragraph("4. Ventricular Function", h1))

    for sub_title, func_defs in [
        ("4.1 Left Ventricle (from Cine SA)", [
            ('LV_EF', 'Ejection Fraction (EF)', '%', '55-70'),
            ('LV_EDV', 'End-Diastolic Volume (EDV)', 'mL', '56-155'),
            ('LV_ESV', 'End-Systolic Volume (ESV)', 'mL', '19-58'),
            ('LV_SV', 'Stroke Volume (SV)', 'mL', '55-100'),
            ('LV_CO', 'Cardiac Output (CO)', 'L/min', '4.0-8.0'),
            ('LV_Mass', 'Myocardial Mass', 'g', '85-190'),
        ]),
        ("4.2 Right Ventricle (from Cine SA)", [
            ('RV_EF', 'Ejection Fraction (EF)', '%', '40-65'),
            ('RV_EDV', 'End-Diastolic Volume (EDV)', 'mL', '88-227'),
            ('RV_ESV', 'End-Systolic Volume (ESV)', 'mL', '35-100'),
            ('RV_SV', 'Stroke Volume (SV)', 'mL', '55-100'),
            ('RV_CO', 'Cardiac Output (CO)', 'L/min', '4.0-8.0'),
        ]),
    ]:
        header_label = sub_title.split(" ", 1)[1].split("(")[0].strip() + " Parameters"
        rows = [[header_label, 'Value', 'Unit', 'Normal Range']]
        for key, name, unit, normal in func_defs:
            val = metrics.get(key)
            if val is not None:
                rows.append([name, _fmt(val), unit, normal])
        if len(rows) > 1:
            story.append(Paragraph(sub_title, h2))
            story.append(_make_table(rows, [2.2*inch, 0.8*inch, 0.7*inch, 1.0*inch]))
            story.append(Spacer(1, 8))

    # 5. Conclusions
    story.append(Paragraph("5. Automated Assessment", h1))
    conclusions = []

    lv_ef = metrics.get('LV_EF')
    if lv_ef is not None:
        if lv_ef >= 50:
            conclusions.append(f"Normal left ventricular systolic function (LVEF: {lv_ef:.1f}%)")
        elif lv_ef >= 40:
            conclusions.append(f"Mild left ventricular systolic dysfunction (LVEF: {lv_ef:.1f}%)")
        elif lv_ef >= 30:
            conclusions.append(f"Moderate left ventricular systolic dysfunction (LVEF: {lv_ef:.1f}%)")
        else:
            conclusions.append(f"Severe left ventricular systolic dysfunction (LVEF: {lv_ef:.1f}%)")

    rv_ef = metrics.get('RV_EF')
    if rv_ef is not None:
        if rv_ef >= 45:
            conclusions.append(f"Normal right ventricular systolic function (RVEF: {rv_ef:.1f}%)")
        elif rv_ef >= 35:
            conclusions.append(f"Mild right ventricular systolic dysfunction (RVEF: {rv_ef:.1f}%)")
        else:
            conclusions.append(f"Moderate-severe right ventricular systolic dysfunction (RVEF: {rv_ef:.1f}%)")

    basal_vals = [metrics.get(f"LV_BS_{i:02d}_mean") for i in range(1, 7)]
    basal_vals = [v for v in basal_vals if v is not None]
    if basal_vals:
        avg_t = sum(basal_vals) / len(basal_vals)
        if avg_t > 12:
            conclusions.append(f"Left ventricular wall thickening (avg basal: {avg_t:.1f}mm)")
        elif avg_t < 6:
            conclusions.append(f"Left ventricular wall thinning (avg basal: {avg_t:.1f}mm)")
        else:
            conclusions.append(f"Normal left ventricular wall thickness (avg basal: {avg_t:.1f}mm)")

    if not conclusions:
        conclusions.append("Automated assessment not available - insufficient data")

    conclusion_text = "<br/>".join([f"&bull; {c}" for c in conclusions])
    conclusion_text += "<br/><br/><i>Note: This report is generated by AI-assisted analysis. Clinical correlation recommended.</i>"
    story.append(Paragraph(conclusion_text, ns))

    doc.build(story)
    print(f"PDF报告已生成: {output_path}")
    return output_path
